### ISSUE TITLE
I keep getting a python error even after a successful run of setup.py

### ISSUE THREAD

**Issue by manoflinux** [katzj/ami-creator#13]
ami-creator 
Traceback (most recent call last):
  File "/usr/local/bin/ami-creator", line 9, in <module>
    load_entry_point('ami-creator==0.3', 'console_scripts', 'ami-creator')()
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 305, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 2244, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 1954, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/local/lib/python2.7/dist-packages/ami_creator-0.3-py2.7.egg/ami_creator/ami_creator.py", line 26, in <module>
    import imgcreate
ImportError: No module named imgcreate

If I run it directly I get a similar error. 

./ami_creator.py 
Traceback (most recent call last):
  File "./ami_creator.py", line 26, in <module>
    import imgcreate
ImportError: No module named imgcreate

Here is the output of the setup. 

python ./setup.py install
running install
install_dir /usr/local/lib/python2.7/dist-packages/
Checking .pth file support in /usr/local/lib/python2.7/dist-packages/
/usr/bin/python -E -c pass
TEST PASSED: /usr/local/lib/python2.7/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
creating ami_creator.egg-info
writing ami_creator.egg-info/PKG-INFO
writing top-level names to ami_creator.egg-info/top_level.txt
writing dependency_links to ami_creator.egg-info/dependency_links.txt
writing entry points to ami_creator.egg-info/entry_points.txt
writing ami_creator.egg-info/PKG-INFO
writing top-level names to ami_creator.egg-info/top_level.txt
writing dependency_links to ami_creator.egg-info/dependency_links.txt
writing entry points to ami_creator.egg-info/entry_points.txt
writing manifest file 'ami_creator.egg-info/SOURCES.txt'
reading manifest file 'ami_creator.egg-info/SOURCES.txt'
writing manifest file 'ami_creator.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-i686/egg
running install_lib
running build_py
creating build
creating build/lib.linux-i686-2.7
creating build/lib.linux-i686-2.7/ami_creator
copying ami_creator/ami_creator.py -> build/lib.linux-i686-2.7/ami_creator
copying ami_creator/**init**.py -> build/lib.linux-i686-2.7/ami_creator
creating build/bdist.linux-i686
creating build/bdist.linux-i686/egg
creating build/bdist.linux-i686/egg/ami_creator
copying build/lib.linux-i686-2.7/ami_creator/ami_creator.py -> build/bdist.linux-i686/egg/ami_creator
copying build/lib.linux-i686-2.7/ami_creator/**init**.py -> build/bdist.linux-i686/egg/ami_creator
byte-compiling build/bdist.linux-i686/egg/ami_creator/ami_creator.py to ami_creator.pyc
byte-compiling build/bdist.linux-i686/egg/ami_creator/**init**.py to **init**.pyc
creating build/bdist.linux-i686/egg/EGG-INFO
copying ami_creator.egg-info/PKG-INFO -> build/bdist.linux-i686/egg/EGG-INFO
copying ami_creator.egg-info/SOURCES.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying ami_creator.egg-info/dependency_links.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying ami_creator.egg-info/entry_points.txt -> build/bdist.linux-i686/egg/EGG-INFO
copying ami_creator.egg-info/top_level.txt -> build/bdist.linux-i686/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/ami_creator-0.3-py2.7.egg' and adding 'build/bdist.linux-i686/egg' to it
removing 'build/bdist.linux-i686/egg' (and everything under it)
Processing distribute-0.6.14-py2.7.egg
creating /usr/local/lib/python2.7/dist-packages/distribute-0.6.14-py2.7.egg
Extracting distribute-0.6.14-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding distribute 0.6.14 to easy-install.pth file
Installing easy_install script to /usr/local/bin
Installing easy_install-2.7 script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/distribute-0.6.14-py2.7.egg
Processing dependencies for distribute==0.6.14
Finished processing dependencies for distribute==0.6.14
Processing ami_creator-0.3-py2.7.egg
creating /usr/local/lib/python2.7/dist-packages/ami_creator-0.3-py2.7.egg
Extracting ami_creator-0.3-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding ami-creator 0.3 to easy-install.pth file
Installing ami-creator script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/ami_creator-0.3-py2.7.egg
Processing dependencies for ami-creator==0.3
Finished processing dependencies for ami-creator==0.3

**Comment by manoflinux** [comment]
Fixed it with this. 
yum install python-imgcreate
